GET https://api.sandbox.midtrans.com/v2/SANBOX-619e09844a6b3/status HTTP/1.1
content-type: application/json
Authorization: Basic U0ItTWlkLXNlcnZlci1sU1lLQ2UzRktjUmRFMEpXbFhJZjMwQ3I6

{

}

###

GET http://localhost:8000/api/midtrans/payments/getStatus/SANBOX-619e09844a6b3